"""add schedules

Revision ID: 821ecd801e75
Revises: 0002_runs_token_usage
Create Date: 2026-09-13 18:57:00.962045

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '821ecd801e75'
down_revision: str | Sequence[str] | None = '0002_runs_token_usage'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('CRON', 'ONE_SHOT', name='schedulekind'), nullable=False),
    sa.Column('cron_expr', sa.String(length=200), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_tz', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('target_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DELETED', name='schedulestatus'), nullable=False),
    sa.Column('apscheduler_job_id', sa.String(length=100), nullable=True),
    sa.Column('next_fire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_status'), ['status'], unique=False)

    op.create_table('schedule_runs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('schedule_id', sa.String(length=26), nullable=False),
    sa.Column('subscriber_user_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='schedulerunstatus'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_runs_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_runs_subscriber_user_id'), ['subscriber_user_id'], unique=False)

    op.create_table('schedule_subscriptions',
    sa.Column('schedule_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('target_json', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'user_id')
    )
    with op.batch_alter_table('schedule_subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_subscriptions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_subscriptions_user_id')

    op.drop_table('schedule_subscriptions')
    with op.batch_alter_table('schedule_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_runs_subscriber_user_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_runs_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_runs_schedule_id'))

    op.drop_table('schedule_runs')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_schedules_owner_user_id'))

    op.drop_table('schedules')
    # ### end Alembic commands ###
